INSERT INTO TASK (TITLE, DESCRIPTION, PRIORITY, STATUS, DELETED, CREATED_AT, UPDATED_AT)
VALUES ('Write unit tests', 'Cover service layer', 'MEDIUM', 'PENDING', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TASK (TITLE, DESCRIPTION, PRIORITY, STATUS, DELETED, CREATED_AT, UPDATED_AT)
VALUES ('Refactor service layer', 'Improve readability', 'LOW', 'PENDING', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TASK (TITLE, DESCRIPTION, PRIORITY, STATUS, DELETED, CREATED_AT, UPDATED_AT)
VALUES ('Implement login API', 'Add JWT auth', 'HIGH', 'PENDING', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
